# -----------------------------------------------------------------------------
# Site settings
# -----------------------------------------------------------------------------
name: Nicole Kaack
email: kaacknicole@gmail.com
description: > # this means to ignore newlines until "url:"
footer_text: >
url:  kaacknicole.github.io
baseurl: # the subpath of your site, e.g. /blog/
last_updated: # leave blank if you don't want to display last updated


# -----------------------------------------------------------------------------
# Collections
# -----------------------------------------------------------------------------
collections:
  Writing:
    output: true
    permalink: /writing/
  Projects:
    output: true
    permalink: /projects/

# -----------------------------------------------------------------------------
# Jekyll settings
# -----------------------------------------------------------------------------

# Build settings
markdown: kramdown
highlighter: pygments

# Includes & excludes
include: ['_pages']
exclude: [vendor]

# Plug-ins
plugins:
    - jekyll-email-protect
    - jekyll-paginate



# -----------------------------------------------------------------------------
# Other settings
# -----------------------------------------------------------------------------
jquery_version: "1.12.4"
katex_version: "0.9.0"
anchorjs_version: "3.2.2"
